spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${JDBC_DATABASE_URL}
spring.datasource.username=${JDBC_DATABASE_USERNAME}
spring.datasource.password=${JDBC_DATABASE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
server.address=0.0.0.0
server.port=${PORT:8080}
app.jwt.secret=${JWT_SECRET}
app.jwt.access-token-expiration-ms=${JWT_ACCESS_TOKEN_EXPIRATION_MS:900000}
app.jwt.refresh-token-expiration-ms=${JWT_REFRESH_TOKEN_EXPIRATION_MS:604800000}
