spring.application.name=spring-commerce
spring.profiles.active=dev
spring.datasource.driver-class-name=<driver-name>
spring.datasource.url=<uri>
spring.datasource.username=<username>
spring.datasource.password=<password>
server.port=<port>
